### ISSUE TITLE
Possible issues with vals in type class instances

### ISSUE THREAD

**Issue by tixxit** [typelevel/spire#178]
Recently found a problem where Field[Number].zero was returning null due to some weird initialization order problem. Essentially this was what it looked like:

```
object Number {
  final val zero: Number = Number(0)
  ...
}

trait NumberIsRing extends Ring[Number] {
  val zero = Number.zero
}
```

Switching the val in the type class instance to a def fixed the problem.

We should make sure this is fixed in all typeclass instances.

**Comment by kevinmeredith** [comment]
This issue sounds similar to this question - http://stackoverflow.com/questions/29306979/unexpected-result-when-overriding-val.

**Comment by kevinmeredith** [comment]
As an aside, I believe that this [question](This issue sounds similar to this question - http://stackoverflow.com/questions/29306979/unexpected-result-when-overriding-val) may pertain to the issue that you had observed.

**Comment by armanbilge** [comment]
Hopefully these are all fixed, and newer Scalas are better about this.
