### ISSUE TITLE
Improving tests, port to property-based where possible

### ISSUE THREAD

**Issue by non** [typelevel/spire#192]
Right there there is a lot of somewhat ad-hoc testing code. We should be using property-based tests where possible, and where impossible we should try to make the tests less ad-hoc.

We should also use matcher style consistently everywhere, rather than relying on `assert`.

**Comment by kschwarz1116** [comment]
Proposing to close as fixed.
The repository today has significantly more property-based tests than [when this was written](https://github.com/typelevel/spire/tree/f9259d0530c71eb95cabe23932dc8d03220ab125/tests/src/test/scala/spire).
