### ISSUE TITLE
Add jet (dual number) support (for automatic differentiation)

### ISSUE THREAD

**Issue by non** [typelevel/spire#231]
There is already some work in this area by Franco Callari, so this issue may just be a placeholder for his eventual work.

Dual numbers would be very useful for implementing automatic differentiation.

**Comment by armanbilge** [comment]
It landed:
https://github.com/typelevel/spire/blob/cfd9db3aca90f1de463b229890d83faf3265e259/core/src/main/scala/spire/math/Jet.scala
