### ISSUE TITLE
Create improved big integer and big decimal classes

### ISSUE THREAD

**Issue by non** [typelevel/spire#27]
It would be interesting to have our own implementation of these classes. Some possible improvements:
1. Smarter context (decimal digit guarantees are annoying with binary representations)
2. Faster implementation (possibly)
3. MIT-licensed implementation
4. Better methods/operators without needing implicits
5. Laziness (possibly)
6. Integration with Rational and Real where appropriate

**Comment by armanbilge** [comment]
Scala stdlib got a better `BigInt` in https://github.com/scala/scala/pull/9628. `BigDecimal` is tracked in https://github.com/typelevel/spire/issues/227.
