### ISSUE TITLE
Order and PartialOrder compare results

### ISSUE THREAD

**Issue by denisrosset** [typelevel/spire#350]
What is their contract ? what are the allowed results ? only -1, 0, 1 for Order and -1.0, 0.0, 1.0 and NaN for PartialOrder, or do we allow any negative and positive values ?

The quick start guide mentions -1,0,1 results, while the documentation in the code (that I've written) states that any negative and positive values are possible.

Let's decide on something and update:
- the comment on the typeclass trait,
- the quick start guide,
- the Discipline laws.

**Comment by non** [comment]
In the public documentation I think we should say "positive value", "negative value", and "zero".

In a developer guide we could encourage developers to use -1, 0, and 1, but we should not require that in our laws and tests.

Does this make sense? What do you think @tixxit ?

**Comment by kschwarz1116** [comment]
Propose to close, [they're cats types](https://www.javadoc.io/static/org.typelevel/spire_2.13/0.18.0-M3/spire/algebra/index.html#Order[A]=algebra.Order[A])
