### ISSUE TITLE
Generic Numeric 0 with Spire 0.8.2 on Scala 2.10

### ISSUE THREAD

**Issue by mdedetrich** [typelevel/spire#404]
Due to dependency reasons, we are forced to support Scala 2.10 as well as Scala 2.11. Although `Spire 0.8.2` is supported for Scala 2.10.0, we came across a discrepancy between the 2 versions of Scala

Assuming you have a `case class` like the following

``` scala
case class SomeContainer[T : Numeric](someField:T, anotherField:T)
```

And you want to generically instantiate the case class with zero's (in our case, we are defining a semigroup on the case class, so we need to define zero), we would do something like this

``` scala
def zero = SomeContainer(0,0)
```

Now this works (using Spire 0.8.2) on Scala 2.11.5, but on Scala 2.10.4, we get a compile error

```
[error]  found   : Int(0)
[error]  required: T
```

Unfortunately using stuff like `Number.zero` doesn't work, since we expect a type of `Numeric` and not `Number`

**Comment by non** [comment]
Hi @mdedetrich,

So, using `0` as a generic zero is powered by an implicit conversion. You can always do the following:

```scala
case class SomeContainer[T](someField:T, anotherField:T)(implicit num: Numeric[T]) {
  def zero = SomeContainer(num.zero, num.zero)
}
```

(The `[T: Numeric]` syntax is just sugar for the implicit parameter.)

Thanks for reporting the issue! I'll look into why the conversion is working for you on 2.11.5 but not 2.10.4. In the meantime, I suggest you use the code I posted to work around the issue. Let me know if you hit other problems.

**Comment by mdedetrich** [comment]
Ah thanks, ended up doing a wrapper like this to get it to work (couldn't put it in a case class because I needed a zero without instantiating the case class first ;) )

```scala
private def zero_[A](implicit num:Numeric[A]):SomeWrapper[A] = SomeWrapper(num.zero,num.zero)
```

**Comment by armanbilge** [comment]
Spire currently supports only Scala 2.13 and 3.
