### ISSUE TITLE
Add method to pretty print Algebraic expression string

### ISSUE THREAD

**Issue by tixxit** [typelevel/spire#430]
Algebraic's `toString` gives a nice, simple approximation of the value. However, for debugging we often want to see the full expression that the `Algebraic` is wrapping. It would be nice to have a method to print the expression (eg. "(3/2).sqrt + (x \* y - root(x^2 - 1, 0))").

**Comment by RatanRSur** [comment]
Hey, I was taking a look at this, is this not already covered by the toExprString method?

**Comment by kschwarz1116** [comment]
This one should be closed in favor of #683. Printing of all types should be consistent.

**Comment by armanbilge** [comment]
The gist of this issues seems to be solved by `toExprString`, although how "pretty" it is is subjective ;)
