### ISSUE TITLE
Fix bug in Algebraic.roots

### ISSUE THREAD

**Issue by rklaehn** [typelevel/spire#478]
Algebraic.roots causes intermittent test failures. The test causing the failures is commented out for now, but obviously this should be fixed.

The test was commented out in 3ae2e44018366ff32d6f38c9a23a1324e393ad3c

**Comment by kschwarz1116** [comment]
Seems to have been fixed by #579 [here's the test](https://github.com/typelevel/spire/commit/feb0d7583dfa3e6ee107542a83617a8b45cbba59#diff-ff75860910e5fe42b3f8e21b0eac8177f510fb344f31033f0701706a881128e5R155-R170)
