### ISSUE TITLE
Add command alias for running the probabilistic tests with a very large n

### ISSUE THREAD

**Issue by rklaehn** [typelevel/spire#486]
There are a number of scalacheck or discipline tests that fail occasionally. These are very annoying especially for new contributors. I have found it useful to occasionally run the scalacheck tests over night with a very large number of iterations locally to find and fix those. This should be an sbt task so we don't have to remember the arcane scalacheck options.

**Comment by kschwarz1116** [comment]
Closing for the same reason as [#665](https://github.com/typelevel/spire/issues/665#issuecomment-1139725205)
