### ISSUE TITLE
Re-publish Caliper with a newer one.

### ISSUE THREAD

**Issue by pocorall** [typelevel/spire#516]
In `build.sbt` SNAPSHOT version of caliper library is retrieved from the specific URL:

```
"com.google.code.caliper" % "caliper" % "1.0-SNAPSHOT" from "http://plastic-idolatry.com/jars/caliper-1.0-SNAPSHOT.jar"
```

This jar is outdated so it does not compatible with guava 18.0. If I run benchmarks, I got this error:

```
[error] Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.io.Closeables.closeQuietly(Ljava/io/Closeable;)V
[error]         at com.google.caliper.Runner.measure(Runner.java:299)
[error]         at com.google.caliper.Runner.runScenario(Runner.java:227)
[error]         at com.google.caliper.Runner.runOutOfProcess(Runner.java:376)
[info]  0% Scenario{vm=java, trial=0, benchmark=AddLongsDirect}
[error]         at com.google.caliper.Runner.run(Runner.java:95)
[error]         at com.google.caliper.Runner.main(Runner.java:421)
[error]         at com.google.caliper.Runner.main(Runner.java:433)
[error]         at spire.benchmark.MyRunner.main(Benchmark.scala:37)
[error]         at spire.benchmark.AddBenchmarks.main(AddBenchmarks.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
```

If I downgrade guava to 15.0 it is OK, as it provides `closeQuietly(Ljava/io/Closeable;)`.

**Comment by malcolmgreaves** [comment]
+1 On this. Currently the benchmarks are broken. On master, `sbt "benchmarks/run-main spire.benchmark.ScalaVsSpireBenchmarks"` runs into this error before showing any output.

**Comment by malcolmgreaves** [comment]
Guava 18 and caliper 1.0-beta-2 did *not* work. Led to 70 compilation errors. Looks like there are many things that are missing (or renamed) from the 1.0-beta-2 version.

**Comment by fosskers** [comment]
This is still an issue.

**Comment by jacobsallan** [comment]
The benchmarks will work with an older version of guava:
    "com.google.guava" % "guava" %  "15.0"
I also tried changing dependencies to those mentioned in caliper web pages, but those web pages seem to be a target rather than a reality.  The activity in the caliper project is very low.  Before it went inactive, there seems to have been a major refactoring of the source code.  For instance, the class that spire benchmarks uses (com.google.caliper.Runner) does not exist in the "next" caliper version.

**Comment by fosskers** [comment]
Someone may wish to rewrite this library's benchmarks using [JMH and its sbt plugin](https://github.com/ktoso/sbt-jmh). That would solve the guava issue.

**Comment by armanbilge** [comment]
https://github.com/typelevel/spire/pull/768
