### ISSUE TITLE
Full documentation for the Interval type?

### ISSUE THREAD

**Issue by FavioVazquez** [typelevel/spire#534]
Hi, I've been trying to find the documentation for the Interval type and all of its content. I saw the Scaladoc but it wasn't very enlightening. Also I did not find full examples and explanations of the functionality of the defined methods or things you can do with them. I've been working with [ValidatedNumerics.jl](https://github.com/dpsanders/ValidatedNumerics.jl) to do physics and computer science, and I'll like to find a way of implementing some functions they have built, like the interval newton method, automatic differentiation, etc., because a saw a talk by @non and I think your code is full of possibilities, also it would be great to have the functionality of some interval arithmetic libraries in other languages in Scala using Spire. 

Is any other source of information apart from this talk I saw?, it was at the Northeast Scala Symposium 2015 by the way. I'm really interested in doing science and physics with this library, specially the Intervals, so if there's a source of information about what are you doing with this, apart from what is in the repo, and if is possible, please let me know.

**Comment by denisrosset** [comment]
Hi @FavioVazquez,

I'm also doing research in physics using Scala. I'm currently using Spire's intervals to store known bounds for quantities in a database (ex: the maximal quantum value of that expression is between this and this). I'm actually using intervals of exact numbers represented as abstract syntax trees (these numbers are not in Spire).

For other projects, I employ interval arithmetic to compute rigorous bounds for various expressions, but I cannot program in Scala, or any JVM language for that. Main reason: the JVM does not support changing the IEEE point rounding modes.

Thus, Spire's `Interval` type should not be used for rigorous computations with floating point numbers. (Rationals or other exact types are perfectly OK).

I will be adding a warning to the Scaladoc.

**Comment by denisrosset** [comment]
I committed the warning. @FavioVazquez, did we clarify the issue for you, or do you think we should keep this issue as an enhancement request?

**Comment by FavioVazquez** [comment]
Thanks @denisrosset for answering and also for letting me know that about the library and the JVM. I think this would be helpful for everyone that uses the library, so it should be marked as an enhancement. I'll be happy to help if is needed.

**Comment by kschwarz1116** [comment]
Propose to close as fixed/not specific enough. Implement another library in spire seems way too broad. Perhaps more specific ideas could go in #292?

**Comment by armanbilge** [comment]
I'm confused what more there is to be done here. Let's close.
