### ISSUE TITLE
error in code snippet in README

### ISSUE THREAD

**Issue by alexland** [typelevel/spire#563]
this is line 467 of the README:

``` Scala
    val rng = Cmc5()
```

lines 470 - 477 are various calls to this object's _next_ method. 

but i can't get line 467 to compile

``` Scala
    %> val rng = Cmwc5()
        Main.scala:586: not found: value Cmwc5
    val rng = Cmwc5()
          ^
    Compilation Failed
```

instead this works fine:

``` Scala
    %>  import spire.random.rng._
    %> val rng = spire.random.rng.Cmwc5()
        rng: Cmwc5 = spire.random.rng.Cmwc5@495e3dd2
    %> val n = rng.next[Double]
        n: Double = 0.6356364854320309
```

i suppose swapping line 467 with the two lines above, should be the simplest fix.

i don't mind submitting a PR, but for something like this it seems awkward; my preference would be an email patc via _git format-patch_
This Project's guidelines apparently allows patches; either is fine by me, just let me know.

**Comment by denisrosset** [comment]
@non tut should check the readme as well.

**Comment by armanbilge** [comment]
Fixed (and under CI) as of https://github.com/typelevel/spire/pull/1047.
