### ISSUE TITLE
Non-deterministic property tests

### ISSUE THREAD

**Issue by ryan-williams** [typelevel/spire#665]
While fixing #661 (and unifying `Complex.abs` and `Complex.norm`, removing [this cryptic TODO](https://github.com/non/spire/blob/v0.14.1/core/shared/src/main/scala/spire/math/Complex.scala#L101)), I'm adding tests and attempting to verify that the tests fail before the fix in addition to passing after the fix.

However, I'm seeing a lot of nondeterminism in various `Complex` tests, for example `ComplexCheck`. 

I thought it was just a matter of [scalatest property-tests' RNG-state not being cleared between tests](https://github.com/scalatest/scalatest/issues/841), but [I'm also seeing random variation in failures just re-running the same test over and over](https://gist.github.com/ryan-williams/caeb70d82a25a65fda909e68bcbb42b7#file-terminal-out-L1-L26).

To reproduce:

```
git clone git@github.com:ryan-williams/spire.git
cd spire
git checkout origin/nondeterministic-test-failures
sbt 'testsJVM/testOnly *.ComplexCheck* -- -z "x / x == 1"'
```

Running the last line a bunch of times will generally show a mix of passes and failures; the failures show different generated values each time, because the RNG is being initialized differently each run.

Dropping a `scala.util.Random.setSeed(123)` into `ComplexCheck` causes it to always pass, while `scala.util.Random.setSeed(124)` always fails with the same generated values:

```
[info] ComplexCheck:
[info] - x / x == 1 *** FAILED *** (1 second, 72 milliseconds)
[info]   ArithmeticException was thrown during property evaluation.
[info]     Message: Division by zero
[info]     Occurred when passed generated values (
[info]       arg0 = 4, // 9 shrinks
[info]       arg1 = 361 // 8 shrinks
[info]     )
```

I am of the mindset that even "random" tests should always run deterministically, and we should set a specific random seed in all tests. Not sure if there's an easy / clean way to do that other than something like `scala.util.Random.setSeed(123)` in each suite.

https://github.com/non/spire/issues/608 / https://github.com/non/spire/pull/653 seem to have run into problems with the nondeterminism as well; I'm sure it's cropped up elsewhere.

**Comment by denisrosset** [comment]
I think that @non is investigating having different levels of robustness when running randomized tests. For example, we could let the test suite run for the night before a release.

All in all, there are pros of having non-deterministic tests: as we rerun the same tests over and over again at each push, even when the underlying has not changed, we exercise different branches.

The associated cost is that code coverage always fluctuates.

**Comment by ryan-williams** [comment]
> The associated cost is that code coverage always fluctuates.

Breaking reproducibility of tests/builds is a high cost! A big point of confusion for me in starting to contribute to Spire was that some tests unrelated to my changes were failing *some of the time*.

> … as we rerun the same tests over and over again at each push, even when the underlying has not changed, we exercise different branches.

Using unrelated PRs and unsuspecting-contributors'-unittest-runs as a delayed/incremental fuzz-testing system is a bad process for gaining confidence in code's correctness 😆

A better way would be to e.g. pass a system-property to tests indicating how many cases to run, *but always from a fixed seed*. 

The CI, or some special nightly build, could be given a high value, while users could use a low value when iterating locally, but, crucially, everyone will always get the same result for a given value/command, and the message to downstream users about what's been tested is much clearer.

**Comment by denisrosset** [comment]
Having spurious test failures is pretty bad for on-boarding collaborators, I fully agree. However, false confidence given by non-failing tests would have been even worse.

BTW, do you know what are the best practices around property testing? I'm sure that Spire is not the only library catching (most of) its bugs in that way.

(Note that I am discussing this issue on its principle, not on the implementation: I do not know whether deterministic property tests are at all possible with ScalaTest/ScalaCheck).

**Comment by ryan-williams** [comment]
> Having spurious test failures is pretty bad for on-boarding collaborators, I fully agree. However, false confidence given by non-failing tests would have been even worse.

I hear that; ofc a high (true-)confidence level is important. To me the right approach is:

1. figure out what % confidence we want in the code being correct
2. figure out how many random test cases we think gets us that percent
3. pick that many cases ([obligatory 😄](https://xkcd.com/221/))
4. define "running tests" as "re-verifying those specific cases" (also how non-property tests generally work)
5. if it takes "too long" to re-verify all the cases, delegate that to a heavier-weight CI process and allow for just sanity-checking a subset during local development

Delaying running the "desired number of cases" from 2. to [random points in the future when contributors try running the tests locally] is a weird kind of uncertainty to inject into the process; for example, if people stop contributing, you stop improving your confidence that code you already checked in long ago is correct 🤔.

If you need more cases than can reasonably be re-run as part of a routine `sbt test`, then a better course of action (IMO!) would be to run a huge number of test cases once, maybe over a few days, and document the results (and how to re-run the experiment reproducibly).

That way, you'd get more certainty that the code is correct (*before* checking it in!) than you'd otherwise get in months/years of passers-by running bits of test for you, and everyone can verify your experiment if they wish.

> BTW, do you know what are the best practices around property testing? I'm sure that Spire is not the only library catching (most of) its bugs in that way.

I definitely don't claim to know what "best practices" are! I assumed people were doing deterministic-random tests because that makes much more sense to me, but maybe I am alone in this outlook! 😄😱 

> (Note that I am discussing this issue on its principle, not on the implementation: I do not know whether deterministic property tests are at all possible with ScalaTest/ScalaCheck).

I believe it can be as simple as calling `Random.setSeed` during Suite-initialization; [I did this in a few places in my recent PRs](https://github.com/non/spire/pull/669/files#diff-d16df57bc5e44ef6c30aafc632701503R13)!

If we were to apply it to all suites, we'd probably like to factor it out to a helper, perhaps including the suite name in the seed; [I did something similar in my {cubic,quartic} solvers recently](https://github.com/hammerlab/math-utils/blob/quartic-1.0.0/cubic/shared/src/test/scala/org/hammerlab/math/polynomial/test/RandomTest.scala#L65-L66), where the tests [verify an estimate of the solvers' error](https://github.com/hammerlab/math-utils/blob/quartic-1.0.0/cubic/shared/src/test/scala/cubic/complex/DoubleTest.scala#L43-L73), where the determinism was especially important.

**Comment by kschwarz1116** [comment]
It seems like over the past couple years, failing seeds get written up as issues, which seems like the right way to go. I think this can be closed.

**Comment by armanbilge** [comment]
Agree. Overall, unrelated failures in CI for PRs seem pretty rare.
