### ISSUE TITLE
Cleanup sprint at nescala 2018

### ISSUE THREAD

**Issue by denisrosset** [typelevel/spire#674]
Spire has been a bit neglected lately. Due to both of us (@denisrosset and @non) being co-located at nescala 2018, we are going through the issues/PRs and doing some spring cleaning.

This is a list of some PR/issues cleaned up during the Sprint. I will edit this first comment as necessary.

Housecleaning
#684 Equality and hashes
#681 Lawless typeclasses
#702 Documentation / microsites

Wishlist / future plans
#691 Stats package
#683 Pretty printing and parsing
#675 Support for linear algebra
#676 Types for vector spaces/modules
#677 Support for multivariate polynomials
#678 Testing improvements

We should discuss this
#326 Coherence in typeclasses
#315 Styleguide: where to put instances, ...
#231 What to do with Jet? (-> move to spire-legacy?)
#437 Jet again

**Comment by non** [comment]
I'm closing this, since modularization will probably supersede it:

https://github.com/non/spire/pull/651

**Comment by armanbilge** [comment]
I don't think there's anything actionable here.
