### ISSUE TITLE
publish for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by SethTisue** [typelevel/spire#742]

**Comment by erikerlandson** [comment]
@SethTisue +1
it is like you read my mind

**Comment by erikerlandson** [comment]
`scalacheck-1.14.0` and `scalatest-3.0.6-SNAP3` are now available for 2.13.0-M5

`machinist` and `algebra` are outstanding

**Comment by denisrosset** [comment]
Seems we are waiting for https://github.com/typelevel/algebra/issues/219

**Comment by SethTisue** [comment]
algebra 1.0.1 is now available for M5

**Comment by stijndehaes** [comment]
I think this ticket can be closed since PR is merged?

**Comment by larsrh** [comment]
It is merged, but not published yet.

**Comment by denisrosset** [comment]
@larsrh I'm travelling as well until Thursday! Would be happy to share the publishing process with you, if we can perform one release together to see how it works.

**Comment by larsrh** [comment]
@denisrosset Sorry, I missed your comment. I'm running a release right now.

For the future, please create a Sonatype account and request publishing rights here: https://issues.sonatype.org/browse/OSSRH-4953

Let me know once you have done so and I will confirm your membership.

**Comment by larsrh** [comment]
0.16.1 is out.
