### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by jdbancal** [typelevel/spire#751]
We need a logo for the spire documentation website.

**Comment by jdbancal** [comment]
Here is a suggestion, using the idea of building towards a spike, subsets, and the traditional typelevel hexagone

![g1945](https://user-images.githubusercontent.com/5440791/50043699-30b93e00-0079-11e9-8309-debc15ac62f5.png)

**Comment by mandyellow** [comment]
Hi there,

I've came up with this logo proposal.

![logo-spire](https://user-images.githubusercontent.com/30158643/50307710-4b782200-0480-11e9-9932-63bc535ba321.png)

**Comment by jdbancal** [comment]
Hi @mandyellow , nice logos, thanks!

Here is a variant of the previous one

![g1540](https://user-images.githubusercontent.com/5440791/50352686-49789680-0546-11e9-9d0f-d44e68ba3193.png)

**Comment by armanbilge** [comment]
Thank you, closing since this is an old issue and I wouldn't know what to do with a logo anyway :)
