### ISSUE TITLE
I Offer a Logo for Spire

### ISSUE THREAD

**Issue by hutriteguh** [typelevel/spire#755]
hello

I don't know if this the appropriate way to offer a logo for this project. I made a logo base on a logo someone else made in another issue. anyway feel free to use the logo for this project.

![image](https://user-images.githubusercontent.com/46064613/50372073-1263bd00-05fa-11e9-9074-3b0fc06cdd07.png)

**Comment by larsrh** [comment]
Hey @hutriteguh, sorry this proposal sat so long. Did you create this logo yourself? Are we free to use it under a permissive license (CC-BY)?

**Comment by armanbilge** [comment]
Thank you, closing since this is an old issue and I wouldn't know what to do with a logo anyway :)
