### ISSUE TITLE
spire.math.Selection has dead code

### ISSUE THREAD

**Issue by denisrosset** [typelevel/spire#766]
`HighBranchingMedianOf5` is used, and `MutatingMedianOf5` is no longer in use.

Benchmark `Mo5Benchmarks` was comparing the two and is commented out.

Benchmark code is being removed as part of benchmark cleanup. See commit e2c4b757654bd30c4576342359ef5ccdab3cc6df

**Comment by denisrosset** [comment]
@non: do you remember what was done for Selection?

**Comment by tixxit** [comment]
@denisrosset wdym when you say "what was done"? I think when I wrote it, I implemented both and benchmarked them and used the faster one. Definitely nice to remove the unneeded code!
