### ISSUE TITLE
parallel Sequence is being shimmed for 2.13 cross-compatability

### ISSUE THREAD

**Issue by erikerlandson** [typelevel/spire#780]
I added a compatibility shim in #759, which is currently only being used in the random forest example.  The goal is to either remove the dependency on parallel sequences entirely, or build against the new separate parallel sequence package dependency (at this time not built against 2.13).

**Comment by SethTisue** [comment]
We'll publish scala-parallel-collections for 2.13.0-RC1. (It requires some post-M5 changes to the collections API.)

**Comment by larsrh** [comment]
I don't like the parallel collections though :wink:

**Comment by erikerlandson** [comment]
Then maybe the goal is `"remove parallel collections" || false` :thinking:

**Comment by larsrh** [comment]
#795 has removed the dependency on the compatibility library. The course of action for this is, accordingly, to split up the examples code or to continue with the compatibility shim in the spirit of #796.

**Comment by kschwarz1116** [comment]
No longer supporting 2.12, I think we can close this one.
