### ISSUE TITLE
Trilean is not a valid Heyting

### ISSUE THREAD

**Issue by vquintin** [typelevel/spire#785]
The `Heyting` instance for `Trilean` is not valid as it does not respect the non-contradiction law:
```
and(not(a), a) == Trilean.False
```
for `a = Trilean.Unknown`

A De Morgan algebra would be more appropriate than a Heyting algebra for `Trilean`
I opened a PR in [typelevel/algebra](https://github.com/typelevel/algebra/pull/224) to add a DeMorgan typeclass there.
If it is accepted, we should update the Trilean code here.

**Comment by larsrh** [comment]
I think for the time being, the offending instance should be removed here.

**Comment by vquintin** [comment]
You merged my PR in [typelevel/algebra](https://github.com/typelevel/algebra/pull/224). As soon as there is a release including it, I will open a PR here.

**Comment by travisbrown** [comment]
As soon as #796 lands this will be ready to go, @vquintin.

**Comment by travisbrown** [comment]
@vquintin Do you want to take this now that #796 is merged and your Algebra change is available? If not I'm happy to.

**Comment by vquintin** [comment]
@travisbrown I'll try to open a PR by the week end, I'll keep you posted !

**Comment by vquintin** [comment]
I opened a PR: https://github.com/typelevel/spire/pull/802

**Comment by kschwarz1116** [comment]
Can close as fixed.
