### ISSUE TITLE
publish for scala 2.13.0

### ISSUE THREAD

**Issue by erikerlandson** [typelevel/spire#805]
scala 2.13.0 released!  \o/

**Comment by pnosko** [comment]
Hey, is there any progress on this? I would like to upgrade to scala 2.13 and this is the only blocker for me. Thanks!

**Comment by Dash-Lambda** [comment]
I'm wondering about the progress too.

**Comment by xuwei-k** [comment]
https://github.com/typelevel/algebra/issues/232

**Comment by larsrh** [comment]
All necessary releases should be out, but I'd appreciate a PR with the updates.

**Comment by gabro** [comment]
--> #806

**Comment by larsrh** [comment]
0.17.0-M1

**Comment by erikerlandson** [comment]
:tada:

**Comment by denisrosset** [comment]
Excellent!
