### ISSUE TITLE
Changelog updates

### ISSUE THREAD

**Issue by DuncanHills** [typelevel/spire#816]
Hi friends, I'm a user of Spire (and potential future contributor). I've noticed that the changelog hasn't been updated since 0.14.1 and the releases have no change notes.

Is there something you all, or I, could do to improve this situation? Secondly, it would be useful to see explicit versioning rules laid out, similar to other typelevel projects like cats. Right now I don't know what the binary/source compatibilities of the different versions are.

Thanks!

**Comment by denisrosset** [comment]
Regarding release notes: the next Spire release (apart from bug fixes) will likely be a significant departure from the current code base. Join https://gitter.im/typelevel/spire-dev to be alerted when work restarts.

We'll get to a 1.0 version at some stage with explicit compatibility guarantees. Expect breakage to occur.

And thanks for your interest!
