### ISSUE TITLE
Does this work on Breeze data types like DenseMatrix and Densevector

### ISSUE THREAD

**Issue by viral612** [typelevel/spire#885]
I am curious to know if the auto differentiation works with datatypes from Breeze project (https://github.com/scalanlp/breeze). 
Is there a good resource to look at some examples of using this package.
Thanks for your help

**Comment by denisrosset** [comment]
Probably not.

Spire has some form of auto differentiation through the `Jet` data type; however I don't know which guarantees it offers; given that it's unprincipled, I don't know how it will interact with Breeze -- if it can be made to work with Breeze at all!

Have a look at the Julia ecosystem, which seems to have more robust support for auto differentiation.
